### ISSUE TITLE
Rename to Data.Task

### ISSUE THREAD

**Issue by robotlolita** [folktale/data.task#20]

**Comment by JemiloII** [comment]
Sooooooo, you renamed it, but `npm install --save data.task` doesn't work, and when you do `npm install --save folktale/data.task` it installs a data.future................. ? Maybe you have an internal npm and didn't notice, maybe? Benefit of the doubt. Side, love the work, Futures/Tasks are awesome, just noticing a bug.

**Comment by JemiloII** [comment]
How do we run these test locally? All i want to do is rename the functions for code clarity whenever debugging or just looking at source. Thanks

**Comment by robotlolita** [comment]
Ah, sorry. I had a few things to fix on the package before releasing a new version.
