### ISSUE TITLE
Provide the `Task#taskify` helper function

### ISSUE THREAD

**Issue by iliocatallo** [folktale/data.task#30]
Hi,

It would be really convenient to augment `Task` so as to include two additional helper methods: `Task#taskify` and `Task#taskifyAll` (similarly to what provided by Bluebird for promises).  This would allow avoiding manual wrapping such as:

```javascript
let connectToMongoDb = mongoUri => new Task((reject, result) => {
    MongoClient.connect(mongoUri, (err, db) => {
        if (err) {
            return reject(err);
        }
        result(db);
    });
});
```
for each single async. function in the codebase.

Thank you!

**Comment by robotlolita** [comment]
`Task#taskify` is already provided by @stoeffel's Futurize library (https://github.com/stoeffel/futurize) :3

I'm particularly against the concept of `Task#taskifyAll` (and `Promise#promisifyAll`, for that matter), since it creates APIs that are not supposed to exist, e.g.:

```js
var events = new EventEmitter();
Task.taskifyAll(events);
events.onAsync(function(){ ... }); // what does this even mean?
```

**Comment by iliocatallo** [comment]
Hi,

thank you for your prompt answer. I understand your concern about the possibility of creating non-sensical APIs. However, in this specific case the price to pay for defending the developer from herself might be too high.
