### ISSUE TITLE
Don't publish test directory to npm

### ISSUE THREAD

**Issue by sotojuan** [folktale/data.task#36]
First of all, I love this library!

Second: When you install this library through npm it downloads the `test` directory, which is unnecessary in production use. I removed it manually and it more than halved the package size (`140kb` to `64kb`).

Developers who need to test the library can clone this repo, so it makes sense to add `test` and whatever else isn't needed for production use to the `npmignore` file.

In case you agree, I am happy to do this myself in a pull request. Thanks!

**Comment by robotlolita** [comment]
Sounds good to me.
